name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name to release (e.g., v1.2.3)
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.vars.outputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true

      - name: Build binaries (linux/amd64)
        run: |
          mkdir -p dist
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags 'netgo' -ldflags '-s -w' -o dist/gitlab-ci-exporter-linux-amd64

      - name: Build binaries (linux/arm64)
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -tags 'netgo' -ldflags '-s -w' -o dist/gitlab-ci-exporter-linux-arm64

      - name: Copy Kubernetes manifest
        run: cp k8s-manifest.yaml dist/

      - name: Checksums
        run: |
          cd dist
          sha256sum gitlab-ci-exporter-* k8s-manifest.yaml > SHA256SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          files: |
            dist/gitlab-ci-exporter-linux-amd64
            dist/gitlab-ci-exporter-linux-arm64
            dist/k8s-manifest.yaml
            dist/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
